version: 'python3.11'
services:
  frontend:
    #build: .
    ports:
      -8501:8501
    environment:
      - server_url='http://127.0.0.1:8000/predict'
    command: streamlit run frontend.py --server.host 8501 --server.address 0.0.0.0
    
    networks:
      - api_server
  backend:
    command: fastapi run --workers 4 --host 0.0.0.0 --ports 8000 backend.py
    network:
      - api_server
    

    



networks:
  api_server:
